language: node_js
node_js: node
cache:
  directories:
    - "$HOME/.npm"
script: npm run build
deploy:
  provider: s3
  access_key_id: ztDf0fCxr0eCgSIi
  secret_access_key:
     secure: cFJaWHHoS0eWjm3ZabzODDT4Px1LC2FKyQuP1Tx4+70AHXYbG+hiS4p3yshP66pMeaJssbPEOmvXiP4YRlTPxYZGua3Go4BVpRM8QlJPHs9Ku5288VyS+RnkhcU9+1a0E13tYYb9GSyYIinQMKSdCG4sqI43U+W5feeCOVPmRaqzqErewEbE4EnV2ZeCkidsEwOTSSeURu0vIl6HAFdXA9rTLN9si1jjqqnDuU1fH2DP3PhQa/e8szT6mPgcSMAh6l7ChYoPCWnNRGLcS00NQStl67uuNA8RNUMSHdNG52WOJesBjtnEonsaNsBSTYFt7oDuJh9a7H2mmKnj3KvcT5HODt/xfdOeUNuviejNRfHguMQ3elauUSskqC9/nIOLzrZL+6yKLmW//iEhEhtPOsY8wGBxgSeS2LusHbUVU512p2lO2Vp0jWc11M7g5eca/tXzHh4cFTU9qKyf20b7T7S2+GDsxOyTJyNL7LKs37rop7siyks3iMbQBv7eexmgzJECN5r9PNWIle2lPpWRypONwbrxSQ0BDypRWp4+zfEhjWlMzDAeItjCG3qI54iMXzUWT1cMGdUDrfvjaPB0q91ftZ1240UU2PsK/7q9eT1kU2ouiXs1NWYrAlaomeFXA8lfVqWbVWABV3hi3VEuC1dyhkjW7iWB0mKv+Wi7P1M=
  bucket: mycard
  skip_cleanup: true
  local-dir: dist
  upload-dir: key
  endpoint: https://minio.mycard.moe:9000
